# Release task
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference
trigger:
  branches:
    include:
      - refs/tags/*

variables:
  - name: githubConnectionName
    value: releases
  - name: projectName
    value: "Akka.Persistence.Sql Test Data"
  - name: githubRepositoryName
    value: akkadotnet/Akka.Persistence.Sql.Exporter
  - name: dockerRepositoryName
    value: akkadotnet
  - name: dockerConnectionName
    value: AkkaDocker

jobs:
  - job:  linuxImageDeploy
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET 6 SDK 6.0.100'
        inputs:
          version: 6.0.100
      - task: Docker@2
        displayName: "Login to Docker Hub"
        inputs:
          command: login
          containerRegistry: $(dockerConnectionName)
      - task: Bash@3
        displayName: Docker Build
        inputs:
          filePath: "./build.sh"
          arguments: --target all --configuration Release --repo $(dockerRepositoryName) --latest --push
        continueOnError: false
      - task: Docker@2
        displayName: Logout of Docker Hub
        inputs:
          command: logout
          containerRegistry: $(dockerConnectionName)
      - task: CopyFiles@2
        displayName: 'Copy export output'
        inputs:
          sourceFolder: bin/
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: export-result          
      - script: 'echo 1>&2'
        failOnStderr: true
        displayName: 'If above is partially succeeded, then fail'
        condition: eq(variables['Agent.JobStatus'], 'SucceededWithIssues')
      - task: GitHubRelease@0
        displayName: 'GitHub release (create)'
        inputs:
          gitHubConnection: $(githubConnectionName)
          repositoryName: $(githubRepositoryName)
          title: '$(projectName) v$(Build.SourceBranchName)'
          releaseNotesFile: 'RELEASE_NOTES.md'
          assets: |
            bin\*.db